version: "3.9"
services:
  aem-sdk:
    image: 'odyssee/aem-sdk-demo'
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:4502"]
      interval: 30s
      timeout: 30s
      retries: 3
    network_mode: "host"
  wknd:
    image: 'odyssee/aem-guides-wknd-graphql-react-app'
    tty: true
    depends_on:
      aem-sdk:
        condition: service_started
    network_mode: "host"
