ARG AEM_VERSION=latest
FROM odyssee/aem-sdk:$AEM_VERSION

# Place the packages into the install folder
COPY packages/demo/* /crx-quickstart/install/

# Start AEM and install packages
RUN /crx-quickstart/bin/start \
        && sleep 1m \
        && (timeout 5m tail -f /crx-quickstart/logs/error.log; exit 0) \
        && /crx-quickstart/bin/stop \
        && sleep 1m
